-- RETIRED CANONICAL ARTIFACT — DO NOT EXECUTE.
--
-- telemetry.telegraf_ingest belonged to the retired bridge-based ingestion
-- model.
--
-- Current canonical persisted ingestion path:
--
--   Telegraf
--      -> public.mqtt_staging insert-only adapter view
--      -> telemetry.raw_messages
--
-- This file intentionally contains no executable SQL. It remains only to
-- document the retired object name and historical deployment sequence.
