FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/workspace/app

WORKDIR /workspace

COPY app/requirements.txt /workspace/app/requirements.txt
COPY app/requirements-dev.txt /workspace/app/requirements-dev.txt

RUN pip install \
    --no-cache-dir \
    --requirement /workspace/app/requirements-dev.txt

COPY pytest.ini /workspace/pytest.ini
COPY app/src /workspace/app/src
COPY app/tests /workspace/app/tests
COPY postgres/ddl /workspace/postgres/ddl
COPY postgres/migrations /workspace/postgres/migrations

CMD ["pytest", "-q", "-p", "no:cacheprovider", "app/tests"]
