FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY requirements-dev.txt /app/requirements-dev.txt

RUN pip install \
    --no-cache-dir \
    --requirement /app/requirements-dev.txt

COPY src /app/src
COPY tests /app/tests

CMD ["pytest", "-q"]
